### ISSUE TITLE
Community link

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux.github.io#1]
Hi, 
Wasn't sure where to put this but the community link (http://termux.com/community/) on the play store doesn't work when using the app. It seems to be linking to http://termux.com/community (without the last slash) and a 404 page appears. It works from the website.

**Comment by fornwall** [comment]
Thanks a lot for noticing - it seems that the play store strips away trailing slashes on links. This has been fixed on the termux.com server now!
