### ISSUE TITLE
Firstofall

### ISSUE THREAD

**Issue by CreaLinu** [termux/termux.github.io#111]
:/ $ Hack phone call and SMS
/system/bin/sh: Hack: inaccessible or not found
127|:/ $
127|:/ $
127|:/ $
127|:/ $
127|:/ $ pkg install git -y
/system/bin/sh: pkg: inaccessible or not found
127|:/ $
127|:/ $ pkg install python -y
/system/bin/sh: pkg: inaccessible or not found
127|:/ $
127|:/ $ git clone https://github.com/TheSpeedX/TBomb.git
/system/bin/sh: git: inaccessible or not found
127|:/ $ cd TBomb
/system/bin/sh: cd: /TBomb: No such file or directory
2|:/ $
2|:/ $ ./TBomb.sh
/system/bin/sh: ./TBomb.sh: inaccessible or not found
127|:/ $
127|:/ $ <Creation0Mode0@gmail.com
/system/bin/sh: can't open Creation0Mode0@gmail.com: No such
 file or directory
1|:/ $ Hack phone call and SMS
/system/bin/sh: Hack: inaccessible or not found
127|:/ $
127|:/ $
127|:/ $
127|:/ $
127|:/ $ pkg install git -y
/system/bin/sh: pkg: inaccessible or not found
127|:/ $
127|:/ $ pkg install python -y
/system/bin/sh: pkg: inaccessible or not found
127|:/ $
127|:/ $ git clone https://github.com/TheSpeedX/TBomb.git
/system/bin/sh: git: inaccessible or not found
127|:/ $ cd TBomb
/system/bin/sh: cd: /TBomb: No such file or directory
2|:/ $
2|:/ $ ./TBomb.sh
/system/bin/sh: ./TBomb.sh: inaccessible or not found
127|:/ $
127|:/ $ name="Creation0Mode0@gmail.[
> Hack phone call and SMS
> $    }
> {
>
> 1
e https://github.com/TheSpeedX/TBomb.git                  <
>
>
>
> @CreaLinuuu
>

**Comment by 2096779623** [comment]
https://wiki.termux.com/wiki/hacking
