### ISSUE TITLE
changelog out of date

### ISSUE THREAD

**Issue by treakiandroid** [termux/termux.github.io#12]
hi,

on https://termux.com/changelog.html version 0.39 is the latest but on https://play.google.com/store/apps/details?id=com.termux its 0.41. Please update that correctly. Also a changelog page for all other projects (api, styling and widget) would be nice to.

Thanks

**Comment by fornwall** [comment]
Thanks, the changelog has been updated (updates to the API, Styling and Widget add-on will be on the same changelog page)!
