### ISSUE TITLE
Node JS .deb not found

### ISSUE THREAD

**Issue by KaisarCode** [termux/termux.github.io#15]
Installing with the command `apt install nodejs` throws:

`Failed to fetch http://termux.net/dists/stable/main/binary-arm/nodejs_6.6.0-1_arm.deb`

The deb file doesn't exists anymore.

Thanks.

**Comment by fornwall** [comment]
This is due to the nodejs package being updated to 6.7! Run

    apt update

first to download the list of available packages before trying again!
