### ISSUE TITLE
stick window to desktop

### ISSUE THREAD

**Issue by dnastase** [termux/termux.github.io#21]
This is a feature request: is it possible that there is a way to not have the window on top of other apps all the time (when it's visible) but it sticks to the desktop like a widget ?
That would allow us to have a terminal that displays things on the desktop. 
So it's basically another type of terminal widget ... true terminal in a widget, not shortcut chooser ...

**Comment by rodrigoaguilera** [comment]
I think now you have https://termux.com/add-on-float.html
