### ISSUE TITLE
Documentation for usage of mosh-server

### ISSUE THREAD

**Issue by timoc** [termux/termux.github.io#28]
You have mosh as part of the termux packages, but no documentation on how to set it up and use the server in the termux shell.

**Comment by Neo-Oli** [comment]
No setup is required. All you need to have is an ssh server. Instructions for that are [here ](https://termux.com/ssh.html)and [here](https://glow.li/tech/2015/11/06/run-an-ssh-server-on-your-android-with-termux.html). Mosh-server starts automatically if required. It's not a daemon that you have to run yourself.
