### ISSUE TITLE
Update termux api docs

### ISSUE THREAD

**Issue by rodrigoaguilera** [termux/termux.github.io#29]
Great piece of software!

I was trying to follow
https://termux.com/add-on-api.html

Specifically termux-notification but there is no -u argument anymore and I don't know where I can find the information to make a PR. I guess I need to read android code.

I ended up using termux-open-url that is not that list.

How can I help to get that page updated without much android knowledge?

For example termux-notification has now a --action flag but I don't know the kind of string I have to pass in there.

Thanks.

**Comment by rodrigoaguilera** [comment]
Is termux moving somewhere. Can you explain why the closing?

**Comment by Neo-Oli** [comment]
@rodrigoaguilera https://termux.com/add-on-api.html Is only for legacy reasons now. As we now have a wiki, where anyone can easily make changes. https://wiki.termux.com/wiki/Termux:API

**Comment by rodrigoaguilera** [comment]
Cool. Thanks for your effort :)
