### ISSUE TITLE
cpuinfo on A53

### ISSUE THREAD

**Issue by matDOTviguier** [termux/termux.github.io#32]
Hello, and Thanks a lot for the Termux stack.

Launched /proc/cpuinfo on a MOTO Z2 PLAY (msm8953, quad A53).
cpuinfo tells the model name is armV7.

The A53 implements armV8-A
Possible a cpuinfo issue ?

Never tested a armv8-A specific code on it, yet.

**Comment by fornwall** [comment]
Hello!

Note that /proc/cpuinfo is provided by the Linux kernel that is part of the Android system - it's not something provided by Termux, so I'm unfortunately not able to help you.
