### ISSUE TITLE
npm install fails if installing in device storage

### ISSUE THREAD

**Issue by muggy8** [termux/termux.github.io#35]
So I granted termux permission for storage under settings and it is now able to see my devices "sdcard" folder (below)

![termux-settings](https://user-images.githubusercontent.com/5509614/35319758-17a347f0-0096-11e8-91d4-45741f96c13d.jpg)

but when i'm working from the device folder (which i do because trying to navigate to some obscure folder that termux calls home is quite annoying every time i want to start working on my script and a root text editor is hard to come by) and try to do npm install, node kicks in and then does the things it's supposed to do and then it throws a permission denied error and is not allowed to write to device storage. I'm not quite sure why this is but here's the output that hopefully will be helpful in pinpointing the issue

![npm-install-error](https://user-images.githubusercontent.com/5509614/35319858-885b8318-0096-11e8-956c-b84e9ff1257d.jpg)
 
Thanks!!

**Comment by Grimler91** [comment]
Android doesn't allow executables in the shared internal storage/sdcard. 
There's nothing we can do about this.
