### ISSUE TITLE
are the commands same as linux termial?

### ISSUE THREAD

**Issue by HACKER097** [termux/termux.github.io#37]
i have been using the android app for a while,and it works perfectly, but on the internet when i look for termux most videos are about linux terminal ,i tried it to run tools like nmap and red hawk and it works and because i have zero experience of using any form or linux , i just want to make sure if the commands are same as linux terminal.please reply ,thank you :-)

**Comment by Grimler91** [comment]
Yes, termux is a terminal emulator that provides packages that are the same as on a gnu/linux computer.

**Comment by HACKER097** [comment]
thank u so much for helping

**Comment by Grimler91** [comment]
@HACKER097 if my answer helped then please close this issue.

**Comment by 1653611988** [comment]
运行hexo失败提示找不到/usr/bin/env，但是是有这个文件的，处理器联发科的，是手机不支持么？

**Comment by xeffyr** [comment]
> /usr/bin/env, but there is this file
Really ? Your Android OS have a /usr directory ?
