### ISSUE TITLE
What about cryptsetup

### ISSUE THREAD

**Issue by mxggithub** [termux/termux.github.io#38]
Hi all. 
I'm thinking about cryptsetup. 
I think that it can be a great plus to manage lots of personal data without Google help. 
Eyes of Big G are everywhere. 
;-)

**Comment by xeffyr** [comment]
This issue could be closed in favor of https://github.com/termux/termux-root-packages/issues/22 and https://github.com/termux/termux-root-packages/pull/23 (PR).
