### ISSUE TITLE
Cannot install Lua socket libraries

### ISSUE THREAD

**Issue by bensh4** [termux/termux.github.io#39]
I tried installing Lua socket libraries. But it's giving an error. Lua.h is missing. :disappointed:
Look the screenshot! ![](https://i.imgur.com/SMIPta7.jpg)

Tried
```
luarocks install luasocket
```
 But after i installed liblua-dev using this command
```
pkg install liblua-dev
```
I got this, check screenshot.:point_down:

![](https://i.imgur.com/w7qHAOx.jpg)  

still can't install the libraries.

**Comment by Grimler91** [comment]
You don't have a c compiler installed. Install clang.

**Comment by bensh4** [comment]
![](https://i.imgur.com/R6OUrte.png)
installed clang. Please tell me whether socket is installed. How to use this? Using require command in Lua?

**Comment by Grimler91** [comment]
I don't know anything about luasocket so can't help you. 

Since you didn't get any error messages it is probably installed.

**Comment by bensh4** [comment]
Still, there's an error at the bottom
```
Build error: src/mime.o
```

**Comment by bensh4** [comment]
Everything done :grinning:
