### ISSUE TITLE
luarocks cannot find ssl.h in /openssl directory

### ISSUE THREAD

**Issue by bensh4** [termux/termux.github.io#41]
![](https://i.imgur.com/QoPT2qT.png)

I want to install LUA HTTP via LUAROCKS.I installed openssl. But when trying to install,it is showing this,

```
luarocks install http
```
it is showing an error

```
Error: Could not find header file for OPENSSL
  No file openssl/ssl.h in /usr/local/include
  No file openssl/ssl.h in /usr/include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install luasec OPENSSL_DIR=/usr/local
```
LOOK SCREENSHOT!

I already have openssl/ssl.h

![](https://i.imgur.com/sjMhYOr.png)

**Comment by Grimler91** [comment]
Please don't open duplicate issues (#40) and also open this kind of issue at github.com/termux/termux-packages instead of at this repo.

Have you tried passing the correct OPENSSL_DIR as the error message suggests?

**Comment by bensh4** [comment]
I close (#40).

**Comment by bensh4** [comment]
I tried that too ![](https://i.imgur.com/7czxA1w.png)

**Comment by bensh4** [comment]
Fixed. Thanks @Grimler91 . Post closed in termux/package repo

**Comment by BhanuPrakash531** [comment]
apt-get install libssl-dev will do the trick
