### ISSUE TITLE
Site blocked

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [termux/termux.github.io#42]
![screenshot_20181219-115905](https://user-images.githubusercontent.com/18211838/50216366-dde7cb00-0385-11e9-8465-2272d6dc366b.png)

**Comment by Neo-Oli** [comment]
This looks like it's being blocked by a firewall in your network. Do you know what kind of firewall is used here?

**Comment by kaeptmblaubaer1000** [comment]
Nope, it's a public wifi by Esprit in Hannover

**Comment by kaeptmblaubaer1000** [comment]
Nope, it's a public wifi by Esprit in Hannover

**Comment by xeffyr** [comment]
> public wifi

Public/Free WiFis are usually are too restrictive. Use VPN.

For me it's obviously working:
![2018-12-19 15-59-10](https://user-images.githubusercontent.com/25881154/50224755-56ab4f00-03a7-11e9-9a41-77914af7918f.png)
