### ISSUE TITLE
termux.com/issues redirect

### ISSUE THREAD

**Issue by JohnVeness** [termux/termux.github.io#47]
Hi, thanks for opening the issues tab here.

I notice that the URL https://termux.com/issues redirects to https://github.com/termux/termux-packages/issues . I wonder if instead it should show a page telling the user to go to https://github.com/termux/termux-packages/issues or to https://github.com/termux/termux-app/issues, depending on what the problem is.

The reason I raise this is because https://termux.com/issues is shown as the place to raise issues when you open the terminal. I followed that link, didn't notice the "termux-packages" bit and reported an issue (https://github.com/termux/termux-packages/issues/5462) which I should have reported/searched for duplicates in the "termux-app" repo instead.

Thanks.

**Comment by xeffyr** [comment]
This is done intentionally. We have lots of repositories (app, add-ons, etc) and most users do not know where is a correct place to open the issue. Also it may be not clear where issue should be opened until we will view logs or other info requested from user.

Termux-packages is a "standard" where we accepting issues and then move to correct place if necessary.

**Comment by JohnVeness** [comment]
OK cool. Is it possible to move issues between repos in github? I wasn't aware.

**Comment by xeffyr** [comment]
Yes, there is a way:
![github](https://user-images.githubusercontent.com/25881154/91225278-0663c300-e72c-11ea-9af8-7cb2610ff123.png)
