### ISSUE TITLE
Screenshots on multiple pages don't work anymore

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux.github.io#7]
Hi, 
I've noticed today that the screenshots on the following pages don't work anymore:

https://termux.com/add-on-float.html
https://termux.com/add-on-styling.html
https://termux.com/add-on-widget.html

**Comment by Neo-Oli** [comment]
Correction: They work in Chrome, but not in other browsers. The reason is, that they are in the .webp format, which most browsers don't support yet. http://caniuse.com/#feat=webp

**Comment by fornwall** [comment]
Aha, interesting! They're links into images from the Play Store - I'll change them to be local images instead.

**Comment by Neo-Oli** [comment]
I investigated this a bit. The Play Store seems to do some User Agent Filtering delivering a PNG for browsers other than chrome. 
Which image gets loaded depends on the `-rw` suffix:
### WebP
https://lh3.googleusercontent.com/yvQF2Jdemixl3ThDOcRmJzFS0W7X7vjpdMn1Jwl0-MNpRhew0Fcv0qH6dsKh6RkP5w=h310-rw

### PNG
https://lh3.googleusercontent.com/yvQF2Jdemixl3ThDOcRmJzFS0W7X7vjpdMn1Jwl0-MNpRhew0Fcv0qH6dsKh6RkP5w=h310
