### ISSUE TITLE
grant external sd card permission

### ISSUE THREAD

**Issue by jyf007** [termux/termux.github.io#9]

**Comment by Neo-Oli** [comment]
Hi, this repository is for the termux.com website. 
For issues relating to the app there is https://github.com/termux/termux-app/issues and for package requests/issues with packages there is https://github.com/termux/termux-packages/issues

You can use the external sd card with 
```
termux-setup-storage
cd ~/storage/external
```
but it is only a specific folder to which termux has access to. General write access is sadly not possible currenlty. See the following issues for more information. 
https://github.com/termux/termux-app/issues/20
https://github.com/termux/termux-app/issues/67

**Comment by jyf007** [comment]
I am so sorry,because my country want our people stay hungry stay foolish.
